version: '3.8'

services:
  test_server:
    build:
      context: .
      dockerfile: docker/test_server/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/opt/app
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: todo_list_db
      DB_NAME: postgres_todo_list
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db

  db:
    container_name: todo_list_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres_todo_list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: